using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NameUtilities
{
    private static List<string> names = new List<string>()
    {
        "Adams",
        "Alexander",
        "Amanda",
        "Anderson",
        "Bennett",
        "Beverly",
        "Bobby",
        "Bonnie",
        "Brooks",
        "Campbell",
        "Carlos",
        "Carol",
        "Carolyn",
        "Carter",
        "Catherine",
        "Chris",
        "Christine",
        "Clark",
        "Coleman",
        "Cooper",
        "Craig",
        "Daniel",
        "Davis",
        "Diane",
        "Edwards",
        "Emily",
        "Flores",
        "Garcia",
        "Gonzales",
        "Gregory",
        "Harris",
        "Hernandez",
        "Howard",
        "Hughes",
        "James",
        "Johnny",
        "Jose",
        "Judy",
        "Kathleen",
        "Kathy",
        "Kenneth",
        "Laura",
        "Lawrence",
        "Lopez",
        "Louise",
        "Marie",
        "Marilyn",
        "Martinez",
        "Michelle",
        "Miller",
        "Michal",
        "Moore",
        "Messi",
        "Morris",
        "Murphy",
        "Parker",
        "Paula",
        "Patterson",
        "Perez",
        "Philip",
        "Powell",
        "Rivera",
        "Robert",
        "Ronaldo",
        "Richardson",
        "Rogers",
        "Shirley",
        "Torres",
        "Victor",
        "Virginia",
        "Walker",
        "Walter",
        "Wilson"
    };
    public static string GetRandomName()
    {
        return names[Random.Range(0, names.Count)];
    }
}
